### PR TITLE
feat: use delphi-logger

### PR DESCRIPTION
**Pull request by dshemetov**
Addresses https://github.com/cmu-delphi/delphi-epidata/issues/1467#issuecomment-2146373051.

Related: https://github.com/cmu-delphi/covidcast-indicators/pull/1970

### Summary:

* update requirements files to use [delphi-logger standalone repo](https://github.com/cmu-delphi/delphi-logger)
* import logger from delphi-logger package instead of relative
* remove duplicate logger.py in this repo
* update delphi-epidata.py client to only depend on logger

### Prerequisites:

- [x] Unless it is a documentation hotfix it should be merged against the `dev` branch
- [x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x] Build is successful
- [x] Code is cleaned up and formatted

### CODE REVIEW

**Comment by dshemetov** [comment]
**SNAG**: [PyPI doesn't accept packages that declare dependencies using direct URLs](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#direct-url-dependencies). This means we'd have to get `delphi-logger` hosted on PyPI.

**Comment by dshemetov** [comment]
Closed in favor of #1486

**Comment by dshemetov** [comment]
Actually, gonna convert this PR to switching the server and acquisition code to use `delphi_utils` as in [George's comment](https://github.com/cmu-delphi/delphi-epidata/issues/1467#issuecomment-2189469399).

**Comment by melange396** [comment]
its up to you, but i think its worth it to create a new PR for the changes

**Pull request closed without merging**
