### PR TITLE
replace references to `delphi.cmu.edu/epidata` with `api.delphi.cmu.edu/epidata`

### PR DESCRIPTION
**Pull request by melange396**
- `delphi.cmu.edu/epidata` proxies to `api.covidcast.cmu.edu/epidata` but this includes an "extra hop" which presents a number of problems:
    - it adds a single point of failure.
    - the resource is not load-balanced but proxies to our load-balanced servers, thus defeating some of the other purposes of load-balancing.
    - complicates logging as the webapp logs will need to be cross referenced with proxy logs to get the full spectrum of information on usage.
    - aggregates any number of users' activity behind one IP address (the address of the proxy) for the purposes of rate limiting.

  - this change should happen in our code (especially client libs) and documentation.  outside of this repository, this includes but is not limited to:
    - https://github.com/cmu-delphi/epidatr/blob/02a688219c0deba8a451de2aa1877ee33a8d5672/R/constants.R#L3
    - https://github.com/cmu-delphi/epidatpy/blob/8659609c960cf1863f7c200ee6da9aa876a33b18/epidatpy/_constants.py#L9
    - likely more in: https://github.com/search?q=org%3Acmu-delphi+%22delphi.cmu.edu%22+language%3AR+OR+language%3Apython+OR+language%3AJavaScript+&type=code
    - ( https://github.com/cmu-delphi/covidcast seems to be ok )
    - ( documentation in https://cmu-delphi.github.io/delphi-epidata/api/README.html#the-api should be changed with this PR )

  - usage of this proxied url is not very high at the moment.  however, we are about to announce our "API Keys" release, which involves changes that will require many users to alter their interactions with our service.  they may choose to use our client libraries or reference our documentation, and it is advantageous for us if they do not increase activity to this proxied URI -- hence the desire to update our references to point to the non-proxied URI before such an announcement.  additionally, a significant portion of our current users still make use of very old versions of client libraries, so it is also important that we update our references sooner rather than later, to prevent users from becoming "cemented" to a newer library that still references the proxied URI.

  - we may want to consider using a hostname other than `api.covidcast.cmu.edu`, perhaps one that is not covid-specific
    - this change can happen in the future, and can be done with DNS aliases (CNAMES or similar)

  - ultimately, once activity to `delphi.cmu.edu/epidata` stops (or drops to a negligible amount), the proxying rule can be disabled or removed.
    - it looks like the config for this may be located here: https://github.com/cmu-delphi/delphi-admin/blob/5b7067c5343072bf4fdebc11d1ffdc00fdfc2644/ansible/templates/web-frontend-prod/web-frontend-main-p.conf.j2#L188-L190

### CODE REVIEW

**Review by dshemetov — APPROVED** [review]
These particular changes look good to me.

`api.covidcast.cmu.edu` seems fine, especially since we can add a new non-covid domain later using CNAMES.

**Review by dshemetov — DISMISSED** [review]

**Review by krivard — APPROVED** [review]
👍

**Review by korlaxxalrok — APPROVED** [review]
:shipit: 💥 👍

**Comment by melange396** [comment]
good catch on the new docs!!!

**Pull request merged**
