### PR TITLE
Sync to www-covidcast release v10.0.0

### PR DESCRIPTION
**Pull request by rzats**
Syncing covidcast_utils files to www-covidcast release v10.0.0.

### CODE REVIEW

**Comment by rzats** [comment]
This is an automated test PR for https://github.com/cmu-delphi/www-covidcast/pull/1216! We may or may not want to merge this - @melange396?

**Comment by melange396** [comment]
it doesnt matter too much either way.  we dont need to because theyre already present in #1155 where they are actually used.  on the other hand, we could merge them in now if you want to try to see what happens when the workflow is run but the files have not changed.

**Review by krivard — COMMENTED** [review]
what is the v.10.0.0 referring to? [www-covidcast is currently in v3.2.5](https://github.com/cmu-delphi/www-covidcast/releases)

**Comment by rzats** [comment]
@krivard this "release version" is arbitrarily picked, since this is just a fully automated test PR. I can rename this PR/commit so there's no confusion about a 10.0.0 actually existing :)

**Review by krivard — COMMENTED** [review]
we should probably close this without merging; if we merge it then #1155 will get confused about trying to add the same files

**Pull request closed without merging**
