### PR TITLE
Enable gzip/brotli compression and caching of API responses

### PR DESCRIPTION
**Pull request by capnrefsmmat**
See #160 -- this will only help if deployed to the AWS API endpoints at api.covidcast.cmu.edu, since those run Apache and the others run nginx.

This assumes we have mod_deflate and mod_brotli available on those servers.

### CODE REVIEW

**Comment by capnrefsmmat** [comment]
Just also added API response caching for 2 hours. This depends on mod_expires and will only apply to the AWS API endpoints, since they run Apache.

**Comment by korlaxxalrok** [comment]
This makes sense, @capnrefsmmat. I need to check to make sure those Apache modules are available.

Also, everything runs Apache, but we have a bit of nginx sitting in front of what we serve on the Delphi primary server. Might see some benefit there as well, but we may need to possibly look at an additional nginx config.

**Comment by capnrefsmmat** [comment]
I can also wrap everything up in the right `IfModule` blocks if that would be useful.

I'd assume that if nginx is serving as reverse proxy, it would pass through any compression and caching headers, but I guess if it doesn't we can fix it.

**Comment by korlaxxalrok** [comment]
I think we'd need to get `brotli`, which should not be a problem. I will do that and then we can proceed 👍

**Comment by capnrefsmmat** [comment]
I don't think mod_brotli is a necessity; DEFLATE compression should be good enough for most purposes. Brotli is just a slightly-faster slightly-smaller compression.

So if it'd take much work to add mod_brotli, we can just delete that line instead.

**Comment by sgratzl** [comment]
any estimate when this one will be merged and available in production?

**Comment by korlaxxalrok** [comment]
Ah! Sorry, I keep falling out of the loop on this one. Let me look quickly this morning to see about the brotli piece and then we can move forward.

**Comment by korlaxxalrok** [comment]
@capnrefsmmat I think it'll take some effort to work mod_brotli into the picture. The best option will be to upgrade Apache to a version that includes it. I'd probably want to take some time to make sure we can do this easily and safely for all the servers that are running it.

So if it isn't a deal breaker maybe we move forward without mod_brotli for now, then follow on with the future task to upgrade Apache.

Reasonable?

**Comment by capnrefsmmat** [comment]
Sounds reasonable. I just pushed a change that uses IfModule around the new directives, so it should be possible to use the htaccess as-is. Then if we install mod_brotli we don't have to change anything in the config, just restart Apache.

I didn't actually test this change, so worth checking the syntax is right, but otherwise I think it should work fine and get gzip compression working.

**Pull request merged**
