### PR TITLE
Creates Youtube-survey doc page

### PR DESCRIPTION
**Pull request by tinatownes**
This is a draft of the Youtube-survey doc page. A lot of information is missing or assumed based off of (https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/fb-survey.html) and some items may very possibly be incorrect. A comment by Katie from a May 4/7/2020 tooling team sprint states: "YouTube 4-question survey - this is essentially a copy of fb-survey without the weighted signals".

### Prerequisites:

- [x] Unless it is a documentation hotfix it should be merged against the `dev` branch
- [x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x] Build is successful
- [x] Code is cleaned up and formatted

### CODE REVIEW

**Comment by nmdefries** [comment]
@tinatownes please review this. Once you think it looks okay, I'll rubber-stamp it.

**Review by nmdefries — APPROVED** [review]

**Comment by tinatownes** [comment]
@nmdefries this looks great, you really found some good info on this mysterious survey.

**Comment by melange396** [comment]
Whoops!  We never added a link to this, so its not browsable (someone will need to have the url for it to know its there).  Perhaps we should add it to this block?  https://github.com/cmu-delphi/delphi-epidata/blob/5678820a76018622aeae31362235a99fbe74ce84/docs/api/README.md?plain=1#L102-L108

**Comment by nmdefries** [comment]
It's showing up okay: [page](https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/youtube-survey.html) -- look at the menu bar on the left side. Also in the [inactive signals auto-generated table of contents](https://cmu-delphi.github.io/delphi-epidata/api/covidcast_inactive_signals.html). It's in COVIDcast, and I think [this](https://cmu-delphi.github.io/delphi-epidata/api/covidcast_licensing.html) is the only place that we manually list COVIDcast sources. Added it there in https://github.com/cmu-delphi/delphi-epidata/pull/1532.

**Comment by melange396** [comment]
derp!  i didnt look in the inactive signals, even though i shouldve...

i think that and the pending addition in #1532 are sufficient.

**Pull request merged**
