### PR TITLE
Add covidcast and covidcast_meta endpoints to clients

### PR DESCRIPTION
**Pull request by pedritom-amzn**
add `covidcast` and `covidcast_meta` endpoints to clients, add integration tests for the python changes, and add documentation to the corresponding api docs. also some other minor fixes.

testing: the new integration tests pass.

### CODE REVIEW

**Comment by pedritom-amzn** [comment]
> quick question: how do you run the new test? (very happy to see testing of course!)

i followed the instructions in https://github.com/cmu-delphi/delphi-epidata/blob/master/docs/epidata_development.md and ran
```
docker run --rm delphi_python python3 -m undefx.py3tester.py3tester --color \
  repos/delphi/delphi-epidata/integrations
```
btw, the other integration tests failed for me for some reason, but i haven't looked deeply into the reasons yet -- the failures didn't seem related to my change.

**Comment by undefx** [comment]
got it, thanks.

the other integration tests will fail if database and web images aren't started up prior to testing. i assume this is the case since you didn't mention them, but correct me if i'm wrong. no big deal, i agree this PR shouldn't have any effect on those tests, which are all on the server side.

if/when i ever get some free time, i might make your new test hit the local docker web server instead of the prod api just to provide some isolation and hopefully make things more self-contained. no action needed from you, just putting this down for posterity and whatnot.

thanks again!

**Comment by pedritom-amzn** [comment]
> the other integration tests will fail if database and web images aren't started up prior to testing. i assume this is the case since you didn't mention them, but correct me if i'm wrong.

yeah, it's strange because both of them are running, but yes, the error i'm getting is that it can't connect to the database. i'll dig into it some more.

> if/when i ever get some free time, i might make your new test hit the local docker web server instead of the prod api just to provide some isolation and hopefully make things more self-contained. no action needed from you, just putting this down for posterity and whatnot.

yeah, i was thinking about that too. since `BASE_URL` is hard-coded in the client files, i decided to leave as-is for now to get the tests out, at the risk of the tests failing if prod is down. i'll create an issue to track the isolation task.

**Comment by undefx** [comment]
Noticed that there's no network flag in your `docker run` command. This could explain why the connection failed. Here's the full command:

```
docker run --rm --network delphi-net delphi_python \
python3 -m undefx.py3tester.py3tester --color \
  repos/delphi/delphi-epidata/integrations
```

Thanks, filing an issue sounds great so we don't lose track of this!

**Comment by pedritom-amzn** [comment]
you're absolutely right! added the network parameter and all the tests succeeded. thanks!

opened [issue #56](https://github.com/cmu-delphi/delphi-epidata/issues/56) to track isolating the tests.

**Pull request merged**
