### PR TITLE
Retrieve the modified DB row count using cursor.rowcount

### PR DESCRIPTION
**Pull request by benjaminysmith**
Previously this always returned None

Improves #415

### CODE REVIEW

**Comment by benjaminysmith** [comment]
Verified this passes unit and integration tests locally.

**Comment by krivard** [comment]
This line is super expensive; does this PR mean we can drop it?
https://github.com/cmu-delphi/delphi-epidata/blob/b512b6b55885cdd5c2485414595184ba259b833e/src/acquisition/covidcast/csv_to_database.py#L196

**Comment by benjaminysmith** [comment]
> This line is super expensive; does this PR mean we can drop it?
> 
> https://github.com/cmu-delphi/delphi-epidata/blob/b512b6b55885cdd5c2485414595184ba259b833e/src/acquisition/covidcast/csv_to_database.py#L196

I believe so, but suggest we merge this version and compare the output first (i.e., the logging of that statement vs. the sum of the new row count) -- given that the python SQL row count behavior is kind of waffly. If it looks good in prod we can switch this line for a sum of the individual counts. wdyt?

**Review by krivard — APPROVED** [review]
looks good!

**Pull request merged**
