### PR TITLE
Mark retired indicators inactive on api documentation

### PR DESCRIPTION
**Pull request by minhkhul**
closes [#1733](https://github.com/cmu-delphi/covidcast-indicators/issues/1733)

### Summary

Marked inactive in this PR: covid_act_now, quidel, usafacts.
Mentioned in [#1734](https://github.com/cmu-delphi/covidcast-indicators/issues/1734) but already marked inactive previously: combo_cases_and_deaths, safegraph_patterns

Tested by running jekyll website locally:
Screenshot 2023-01-17 at 2 31 54 PM

### CODE REVIEW

**Review by krivard — CHANGES_REQUESTED** [review]
Changes to covid-act-now.md and usa-facts.md are good.

Changes to quidel.md need adjustment: only the flu signals are inactive. We can either:
* leave quidel.md alone, since the last issue date May 19, 2020 is already there, or
* move the flu signals to a new quidel-inactive.md page (see [safegraph.md](https://github.com/cmu-delphi/delphi-epidata/blob/335f037a2e61e3e9e52dc16680a13d674f7c6ebe/docs/api/covidcast-signals/safegraph.md) and [safegraph-inactive.md](https://github.com/cmu-delphi/delphi-epidata/blob/335f037a2e61e3e9e52dc16680a13d674f7c6ebe/docs/api/covidcast-signals/safegraph-inactive.md) for an example)

**Comment by minhkhul** [comment]
Modified quidel.md under Data Sources and Signals:
Screenshot 2023-01-17 at 4 46 06 PM

Added quidel-inactive.md under Inactive Signals:
Screenshot 2023-01-17 at 4 47 23 PM

Remove safegraph.md as both Social Distancing Metrics and Weekly patterns are now inactive. All safegraph docs are now under inactive signals in safegraph-active.md

**Review by krivard — DISMISSED** [review]
Good catch on the lingering safegraph file!

Fixed a copypasta but otherwise good to go.

**Review by krivard — APPROVED** [review]
github 🤖 i know you're trying to help but it was my commit, so my review still stands

**Pull request merged**
