### PR TITLE
updates to address JHU is_latest (issue #329)

### PR DESCRIPTION
**Pull request by melange396**
this should do the trick, but updating by id instead of the join coming shortly

### CODE REVIEW

**Comment by melange396** [comment]
sorry, that is for https://github.com/cmu-delphi/covidcast-indicators/issues/329 (in another repo)

**Review by krivard — APPROVED** [review]
lgtm

**Comment by krivard** [comment]
oh wait by 'coming shortly' did you mean to add on to this PR? Sorry for the itchy merge finger :(

open a new one and set it as "draft" so I don't come through and stomp on everything again 🙏

**Comment by melange396** [comment]
no worries, i was planning to deliver it along-side anyway

**Pull request merged**
