### PR TITLE
facility fix and new endpoint

### PR DESCRIPTION
**Pull request by dfarrow0**
- `bool('false')` is `True`
- add a helper function to parse bool from str, allowing missing and 
empty values

note that prod database needs to be backfilled since previous 
acquisitions incorrectly casted 'false' and 'true' both to `True`

---

- the hhs covid hosp dataset is keyed by `hospital_pk`, which is a 
unique identifier for healthcare facilities.
- the key is not generally well-known, but querying the 
`covid_hosp_facility` dataset requires key(s)
- the new endpoint returns facility information (including key) for 
given regions (e.g. city, state, zip, ccn, fips)
- users would be expected to lookup hospitals of interest e.g. by state 
or city. then query `covid_hosp_facility` with the key for those 
hospitals.
- server and clients updated
- all unit and integrations pass

note that new indexes are added to the database to facilitate fast 
lookups. otherwise it would be a full table scan each time, which does 
not scale well. indexes are expected to be very small.

### CODE REVIEW

**Review by chinandrew — APPROVED** [review]
:shipit::shipit::shipit:

**Comment by chinandrew** [comment]
does a list of states work here or do they have to be individual?

**Comment by dfarrow0** [comment]
here they would be individual states. i'm not opposed to making that a list of states if it's useful, but prefer to defer that as a followup

**Comment by chinandrew** [comment]
> here they would be individual states. i'm not opposed to making that a list of states if it's useful, but prefer to defer that as a followup

makes sense, sounds fine to leave as is

**Pull request merged**
