### PR TITLE
ci: add release helper

### PR DESCRIPTION
**Pull request by sgratzl**
for releasing to pypi and npm + sync dev/main

**Prerequisites**:

- [x] Unless it is a documentation hotfix it should be merged against the `dev` branch
- [x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x] Build is successful
- [x] Code is cleaned up and formatted

### Summary

add a release helper workflow (pipeline) similar to www-main and others. steps taken

 * use release-drafter (like www-main) to create release notes and git tag
 * publish epidata client to PyPi -> requires `PYPI_API_TOKEN` secret
 * publish epidata JS client to NPM -> requires `NPM_TOKEN` secret -> do we have an account?
 * create a PR that merges the main back to dev

In addition, small tunings for the definition of the Epidata JS client

### CODE REVIEW

**Comment by sgratzl** [comment]
if we want better release-notes we could add more labels to Pull Requests, e.g. we could separate between: 

 * server
 * acquisition
 * python client
 * Javascript client
 * R client
 * documentation
 * chore

**Comment by krivard** [comment]
@korlaxxalrok I added the delphi-epidata PyPI token to LastPass. Would you add that to the env secrets, and work with @christymelucci to set us up with NPM?

**Comment by korlaxxalrok** [comment]
@krivard Yup, will do. PYPI tokens have been added to org secrets.

**Comment by korlaxxalrok** [comment]
@sgratzl `DELPHI_NPM_TOKEN` token is added to org secrets.

**Review by krivard — DISMISSED** [review]
good to go once conflicts are resolved

**Comment by sgratzl** [comment]
> good to go once conflicts are resolved

resolved

**Review by krivard — APPROVED** [review]
👍

**Pull request merged**
