### PR TITLE
API key server logic

### PR DESCRIPTION
**Pull request by sgratzl**
**Prerequisites**:

- [x] Unless it is a documentation hotfix it should be merged against the `dev` branch
- [x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x] Build is successful
- [x] Code is cleaned up and formatted

### Summary

implements the server logic to require API keys and roles for the endpoints. 

tasks
- [x] check for api key
- [x] show a soft warning
- [x] show a hard warning
- [x] adapt tests
- [ ] create tests
- [x] admin interface? 
- [?] log / track api_key + query if allowed
- [x] create basic google form
- [x] connect google form with api server handling -> webhook
- [x] create a basic request a key form: /admin/create_key
- [x] use [flask-limited](https://flask-limiter.readthedocs.io) for rate limiting
- [ ] setup a Redis DB for shared rate limit tracking
- [ ] define a good default rate limit
- [ ] consider using Redis DB also for account management instead of SQL server

### CODE REVIEW

**Comment by sgratzl** [comment]
basic admin interface:

image

`/admin/`

**Comment by sgratzl** [comment]
> [ ] setup a Redix DB for shared rate limit tracking

@korlaxxalrok heads up we are going to need some kind of redis like database that is accessible from all web server nodes

**Comment by korlaxxalrok** [comment]
@sgratzl What URL will we expose the admin interface at?

**Comment by sgratzl** [comment]
> @sgratzl What URL will we expose the admin interface at?

so far the plan is on delphi.cmu.edu/epidata/admin/ which is connected to the master database. Thus, when you edit users it should get replicated to the other databases.

**Comment by korlaxxalrok** [comment]
@sgratzl Re Redix DB. Can we use Redis?

**Comment by sgratzl** [comment]
> @sgratzl Re Redix DB. Can we use Redis?

lol. I should watch out more for typos. Sure, it should be a Redis-compatible database. see also https://limits.readthedocs.io/en/latest/storage.html#storage-scheme

**Comment by krivard** [comment]
superceded by #1061

**Pull request closed without merging**
